### PR TITLE
manifests: added lv_zephyr url for creation of the zephyr based projects

### PR DESCRIPTION
**Pull request by uLipe**
Also added the Zephyr logo.

### CODE REVIEW

**Review by liamHowatt — COMMENTED** [review]
`manifest_all_v1.1.0.json` is not edited directly. A GitHub Action runs every 12 hours to update it automatically. https://github.com/lvgl/lvgl_project_creator/actions

**Comment by uLipe** [comment]
@liamHowatt thanks for that, I was wondering if the manifests should be generated using the python script or if the actions would be responsible for that.

Now it is clear :)

**Comment by uLipe** [comment]
Removed the conflicts and added esp32 based board PTAL again

**Comment by kisvegabor** [comment]
Looks good in general! I love the simplicity of the Zephyr project.

@richardgazdik please take a look at the logo.

Why do you call `lv_timer_handler()` [here](https://github.com/uLipe/lv_zephyr/blob/main/application/src/main.c#L31). If it's a workaround please add a comment. 

[Here](https://github.com/uLipe/lv_zephyr/blob/main/manifests/imxrt1170-evk.json#L39) it has full Markdown support, so you can use a link too. Now there is an issue with the links though: they open in the window of the project creator an not in a browser. @richardgazdik will fix it this week.

**Comment by uLipe** [comment]
Folks any update here?

**Comment by kisvegabor** [comment]
Please transfer the `lv_zephyr` repo to @kisvegabor so that I can transfer it to `lvgl`. 
Don't forget to update the repo urls to `lvgl/lv_zephyr`.

**Comment by uLipe** [comment]
Ohh my bad, I forgot to update the manifests urls :(

**Comment by kisvegabor** [comment]
You still have write access, so you can update it without any issues.

**Comment by uLipe** [comment]
@liamHowatt , @kisvegabor  just updated the manifests to point to the lvgl org instead of mine, PTAL again

**Comment by kisvegabor** [comment]
Looks good, thank you!

**Pull request merged**
